/* tslint:disable */
/* eslint-disable */
/**
 * Perry Chick API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StringStringStringStringfAnonymousType2
 */
export interface StringStringStringStringfAnonymousType2 {
    /**
     * 
     * @type {string}
     * @memberof StringStringStringStringfAnonymousType2
     */
    databaseUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringStringStringStringfAnonymousType2
     */
    frontendUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringStringStringStringfAnonymousType2
     */
    keycloakUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringStringStringStringfAnonymousType2
     */
    keycloakClientId?: string | null;
}

/**
 * Check if a given object implements the StringStringStringStringfAnonymousType2 interface.
 */
export function instanceOfStringStringStringStringfAnonymousType2(value: object): value is StringStringStringStringfAnonymousType2 {
    return true;
}

export function StringStringStringStringfAnonymousType2FromJSON(json: any): StringStringStringStringfAnonymousType2 {
    return StringStringStringStringfAnonymousType2FromJSONTyped(json, false);
}

export function StringStringStringStringfAnonymousType2FromJSONTyped(json: any, ignoreDiscriminator: boolean): StringStringStringStringfAnonymousType2 {
    if (json == null) {
        return json;
    }
    return {
        
        'databaseUrl': json['databaseUrl'] == null ? undefined : json['databaseUrl'],
        'frontendUrl': json['frontendUrl'] == null ? undefined : json['frontendUrl'],
        'keycloakUrl': json['keycloakUrl'] == null ? undefined : json['keycloakUrl'],
        'keycloakClientId': json['keycloakClientId'] == null ? undefined : json['keycloakClientId'],
    };
}

export function StringStringStringStringfAnonymousType2ToJSON(json: any): StringStringStringStringfAnonymousType2 {
    return StringStringStringStringfAnonymousType2ToJSONTyped(json, false);
}

export function StringStringStringStringfAnonymousType2ToJSONTyped(value?: StringStringStringStringfAnonymousType2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'databaseUrl': value['databaseUrl'],
        'frontendUrl': value['frontendUrl'],
        'keycloakUrl': value['keycloakUrl'],
        'keycloakClientId': value['keycloakClientId'],
    };
}

