/* tslint:disable */
/* eslint-disable */
/**
 * Perry Chick API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StringDateTimeStringfAnonymousType1
 */
export interface StringDateTimeStringfAnonymousType1 {
    /**
     * 
     * @type {string}
     * @memberof StringDateTimeStringfAnonymousType1
     */
    status?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StringDateTimeStringfAnonymousType1
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof StringDateTimeStringfAnonymousType1
     */
    version?: string | null;
}

/**
 * Check if a given object implements the StringDateTimeStringfAnonymousType1 interface.
 */
export function instanceOfStringDateTimeStringfAnonymousType1(value: object): value is StringDateTimeStringfAnonymousType1 {
    return true;
}

export function StringDateTimeStringfAnonymousType1FromJSON(json: any): StringDateTimeStringfAnonymousType1 {
    return StringDateTimeStringfAnonymousType1FromJSONTyped(json, false);
}

export function StringDateTimeStringfAnonymousType1FromJSONTyped(json: any, ignoreDiscriminator: boolean): StringDateTimeStringfAnonymousType1 {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function StringDateTimeStringfAnonymousType1ToJSON(json: any): StringDateTimeStringfAnonymousType1 {
    return StringDateTimeStringfAnonymousType1ToJSONTyped(json, false);
}

export function StringDateTimeStringfAnonymousType1ToJSONTyped(value?: StringDateTimeStringfAnonymousType1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'version': value['version'],
    };
}

