/* tslint:disable */
/* eslint-disable */
/**
 * Perry Chick API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StringStringStringDateTimefAnonymousType0
 */
export interface StringStringStringDateTimefAnonymousType0 {
    /**
     * 
     * @type {string}
     * @memberof StringStringStringDateTimefAnonymousType0
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringStringStringDateTimefAnonymousType0
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StringStringStringDateTimefAnonymousType0
     */
    environment?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StringStringStringDateTimefAnonymousType0
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the StringStringStringDateTimefAnonymousType0 interface.
 */
export function instanceOfStringStringStringDateTimefAnonymousType0(value: object): value is StringStringStringDateTimefAnonymousType0 {
    return true;
}

export function StringStringStringDateTimefAnonymousType0FromJSON(json: any): StringStringStringDateTimefAnonymousType0 {
    return StringStringStringDateTimefAnonymousType0FromJSONTyped(json, false);
}

export function StringStringStringDateTimefAnonymousType0FromJSONTyped(json: any, ignoreDiscriminator: boolean): StringStringStringDateTimefAnonymousType0 {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'version': json['version'] == null ? undefined : json['version'],
        'environment': json['environment'] == null ? undefined : json['environment'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function StringStringStringDateTimefAnonymousType0ToJSON(json: any): StringStringStringDateTimefAnonymousType0 {
    return StringStringStringDateTimefAnonymousType0ToJSONTyped(json, false);
}

export function StringStringStringDateTimefAnonymousType0ToJSONTyped(value?: StringStringStringDateTimefAnonymousType0 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'version': value['version'],
        'environment': value['environment'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

